"use client";
import Head from "next/head";
import { useState, useEffect } from "react";
import { animate, motion, useScroll, useTransform} from "framer-motion";
export const MotionDiv = motion.div;
import {AiFillLinkedin, AiFillGithub,} from "react-icons/ai";
import Contact from './Contact';

function Navbar(){
  useEffect(() => {
    const navLinks = document.querySelectorAll('nav a');

    navLinks.forEach(link => {
      link.addEventListener('click', (event) => {
        event.preventDefault();
        const targetId
  = link.getAttribute('href').substring(1);
        const targetElement = document.getElementById(targetId);

        if(targetElement) {
          window.scrollTo({
            top: targetElement.offsetTop,
            behavior: 'smooth'
          });
        }
      });
    });
  })
}

const fadeInAnimationVariants = {
  initial: {
    opacity: 0,
    y: 100,
  },
  animate: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 1
    },
  },
};

export default function Home() {
  return (
    <div>
      <Head>
        <title>{`Juwayriya's Website`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <section id="home" className="min-h-screen bg-[url('/webbackground.jpeg')] bg-cover bg-center overflow-hidden relative z-20">
          <nav className="fixed top-0 left-0 w-full text-white py-10 mb-12 flex justify-between px-12 z-60">
          <h1 className="text-6xl">jr</h1>
            <ul className="flex items-center justify-between gap-18">
              <li className="nav">
                <button className="bg-transparent">
                  <a href="#home">Home</a>
                </button>
              </li>
              <li className="nav">
                <button className="bg-transparent">
                  <a href="#about">About</a>
                </button>
              </li>
              <li className="nav">
                <button>
                  <a href="#projects">Projects</a>
                </button>
              </li>
              <li className="nav">
                <button>
                  <a href="#contact">Contact</a>
                </button>
              </li>
            </ul>
          </nav>
          <div className="p-5"></div>
          <motion.h1 className="text-white text-3xl flex justify-center mt-60 p-10"
             initial={{ opacity: 0, scale: 0.8 }}
             animate={{ opacity: 1, scale: 1 }}
             transition={{ duration: 2, ease: 'easeInOut' }}
           >
            {`Hi, I'm`}</motion.h1>
          <motion.h1 className="text-white text-9xl flex justify-center"
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 2, ease: 'easeInOut', delay: 1.2 }}
          >
            Juwayriya</motion.h1>
          <div className="absolute bottom-4 left-0 right-0 mx-auto text-2xl flex justify-center items-center gap-10 text-white max-w-xl md:text-xl">
            <a href="https://www.linkedin.com/in/juwayriya-rizwan-201974311/" target="_blank" rel="noopener noreferrer">
              <AiFillLinkedin/>
            </a>
            <a href="https://github.com/juwayriyarizwan" target="_blank" rel="noopener noreferrer">
              <AiFillGithub/>
            </a>
          </div>
        </section>
        <section id="about" className="relative min-h-screen bg-[#292728] justify-center overflow-visible">
          <div className="absolute inset-0 bg-[#292728]"></div>
          <div className="relative z-10">
            <motion.h1 className="text-white text-6xl p-40 flex flex-col justify-center items-center"
              variants={fadeInAnimationVariants}
              initial="initial"
              whileInView="animate"
            >
              About Me</motion.h1>
            <motion.div className="bg-white text-black flex flex-wrap bg-opacity-100 -mt-20 p-10 z-10 rounded-lg shadow-lg mx-auto max-w-3xl md:px-12"
              variants={fadeInAnimationVariants}
              initial="initial"
              whileInView="animate"
            >
              <p className="indent-4 leading-relaxed">
              Hey, there! My name is Juwayriya Rizwan and I recently graduated
              from the University of Houston with a degree in Computer Science.
              As an avid programmer with a keen interest in data science and a 
              strong foundation in Python, I enjoy building web applications and
              analyzing data that could help solve real-world problems. Whether
              it’s creating a seamless user experience or tackling backend challenges, 
              I love bringing ideas to life through technology.
              </p>
              < br />
              <p className="indent-4 leading-relaxed">
              {`Collaboration plays a key role in my work, 
              and I thrive in team environments where we can share knowledge 
              and build something impactful together.
              I love bringing ideas to life through technology and I'm always looking 
              for ways to improve my craft.
              My love for coding, combined with my ability to collaborate effectively, 
              makes me a driven and versatile developer.`}
              </p>
            </motion.div>
            <div className="absolute" style={{ left: '250.6px', top: '585.36px' }}>
              <img 
                src="/star.jpeg" 
                alt="star"
                style={{ opacity: 0.2, height: '199px', width: '199px'}}
              />
            </div>
            <div className="absolute" style={{ left: '794.6px', top: '615.36px' }}>
              <img 
                src="/ahhh!.jpeg" 
                alt="ahhh"
                style={{ opacity: 0.2, height: '158px', width: '199px'}}
              />
            </div>
            <div className="absolute" style={{ left: '12px', top: '480px' }}>
              <img 
                src="/bus.jpeg" 
                alt="bus"
                style={{ opacity: 0.2, height: '210px', width: '210px'}}
              />
            </div>
            <div className="absolute" style={{ left: '465px', top: '158px' }}>
              <img 
                src="/vinyl.jpeg" 
                alt="vinyl"
                style={{ opacity: 0.2, height: '361px', width: '289px'}}
              />
            </div>
            <div className="absolute" style={{ left: '250px', top: '330px' }}>
              <img 
                src="/city.jpeg" 
                alt="city"
                style={{ opacity: 0.2, height: '240px', width: '197px'}}
              />
            </div>
            <div className="absolute" style={{ left: '-2px', top: '189px' }}>
              <img 
                src="/newspaper.jpeg" 
                alt="newspaper"
                style={{ opacity: 0.2, height: '275px', width: '215px'}}
              />
            </div>
            <div className="absolute" style={{ left: '24px', top: '-102px' }}>
              <img 
                src="/eiffel.jpeg" 
                alt="eiffel"
                style={{ opacity: 0.2, height: '270px', width: '178px'}}
              />
            </div>
            <div className="absolute" style={{ left: '232px', top: '-51px' }}>
              <img 
                src="/camerimage.jpeg" 
                alt="camerimage"
                style={{ opacity: 0.2, height: '197px', width: '246px'}}
              />
            </div>
            <div className="absolute" style={{ left: '273px', top: '170px' }}>
              <img 
                src="/blueberries.jpeg" 
                alt="blueberries"
                style={{ opacity: 0.2, height: '147px', width: '148px'}}
              />
            </div>
            <div className="absolute" style={{ left: '522px', top: '-94px' }}>
              <img 
                src="/palmtree.jpeg" 
                alt="palmtree"
                style={{ opacity: 0.2, height: '233px', width: '229px'}}
              />
            </div>
            <div className="absolute" style={{ left: '786.6px', top: '12.36px' }}>
              <img 
                src="/reality.jpeg" 
                alt="reality"
                style={{ opacity: 0.2, height: '159px', width: '229px'}}
              />
            </div>
            <div className="absolute" style={{ left: '775px', top: '190px' }}>
              <img 
                src="/greenscreen.jpeg" 
                alt="greenscreen"
                style={{ opacity: 0.2, height: '161px', width: '248px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1038px', top: '-135px' }}>
              <img 
                src="/footsteps.jpeg" 
                alt="footsteps"
                style={{ opacity: 0.2, height: '369px', width: '199px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1033px', top: '250px' }}>
              <img 
                src="/boring.jpeg" 
                alt="boring"
                style={{ opacity: 0.2, height: '310px', width: '206px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1256px', top: '382px' }}>
              <img 
                src="/tdps.jpeg" 
                alt="tdps"
                style={{ opacity: 0.2, height: '349px', width: '233px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1273px', top: '115px' }}>
              <img 
                src="/people.jpeg" 
                alt="people"
                style={{ opacity: 0.2, height: '238px', width: '190px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1269px', top: '-84px' }}>
              <img 
                src="/orange.jpeg" 
                alt="orange"
                style={{ opacity: 0.2, height: '168px', width: '166px'}}
              />
            </div>
            <div className="absolute" style={{ left: '789px', top: '398px' }}>
              <img 
                src="/clockman.jpeg" 
                alt="clockman"
                style={{ opacity: 0.2, height: '172px', width: '215px'}}
              />
            </div>

          </div>
        </section>
        <section id="projects" className="relative min-h-screen bg-[#292728] justify-center overflow-visible">
          <div className="absolute inset-0 bg-[#292728]"></div>
          <div className="relative z-10">
            <motion.h1 className="text-white text-6xl p-40 flex justify-center items-center text-center"
              variants={fadeInAnimationVariants}
              initial="initial"
              whileInView="animate"
            >
              Projects</motion.h1>
            <div className="flex justify-center items-center gap-20 overflow-visible">
              <motion.div className="bg-white p-8 opacity-90 rounded-lg shadow-lg max-w-md z-10"
                variants={fadeInAnimationVariants}
                initial="initial"
                whileInView="animate"
              >
                <h2 className=" flex text-2xl mb-4">Cell Phone Service</h2>
                <p>A comprehensive backend and frontend framework designed
                 to streamline cell phone service operations. Leveraging PostgreSQL for
                  robust data management, the system enables efficient data handling,
                  query processing, and integration with customer service management.</p>
                  <a href="https://github.com/juwayriyarizwan/Cellphone-Company" 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="text-blue-500 hover:underline">View on GitHub</a>
              </motion.div>
              <motion.div className="bg-white p-8 opacity-90 rounded-lg shadow-lg max-w-md z-10"
                variants={fadeInAnimationVariants}
                initial="initial"
                whileInView="animate"
              >
                <h2 className=" flex text-2xl mb-4">Fuel Flow</h2>
                <p>A web application designed to calculate fuel usage. Leveraging EJS for
                  dynamic rendering, the project provides a seamless user interface and
                  interactive experience. MongoDB is utilized to efficiently store and 
                  manage user data, ensuring scalability and room for future enhancements.</p>
                  <a href="https://github.com/juwayriyarizwan/Fuel-Flow" 
                  target="_blank" 
                  rel="noopener noreferrer" 
                  className="text-blue-500 hover:underline">View on GitHub</a>
              </motion.div>
            </div>
            <div  className="absolute" style={{ left: '884.13px', top: '651.62px' }}>
              <img 
                src="/strawberry.jpeg" 
                alt="strawberry"
                style={{ opacity: 0.2, height: '325px', width: '183px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1103.13px', top: '486.62px' }}>
              <img
                src="/shibuya.jpeg"
                alt="shibuya"
                style={{opacity: 0.2, height: '270px', width: '180px'}}
              />
            </div>
            <div className="absolute" style={{ left: '1001.13px', top: '135.62px' }}>
              <img
                src="/outoftime.jpeg"
                alt="time"
                style={{opacity: 0.2, height: '316px', width: '237px'}}
              />
            </div>
            <div className="absolute" style={{left: '794.13px',  top: '30.62px' }}>
              <img
                src="/eternalsunshine.jpeg"
                alt="sunshine"
                style={{opacity: 0.2, height: '225px', width: '180px'}}
              />
            </div>
            <div className="absolute" style={{left: '220.13px',  top: '508.62px'}}>
              <img
                src="/fearless.jpeg"
                alt="fearless"
                style={{opacity: 0.2, height: '325px', width: '226px'}}
              />
            </div>
            <div className="absolute" style={{left: '478.13px',  top: '-224.38px'}}>
              <img
                src="/MORNING!.jpeg"
                alt="morning"
                style={{opacity: 0.2, height: '346px', width: '290px'}}
              />
            </div>
            <div className="absolute" style={{left: '249.13px',  top: '35.62px'}}>
              <img
                src="/music.jpeg"
                alt="music"
                style={{opacity: 0.2, height: '297px', width: '197px'}}
              />
            </div>
            <div className="absolute" style={{left: '-46.87px',  top: '244.62px'}}>
              <img
                src="/cia.jpeg"
                alt="ciao"
                style={{opacity: 0.2, height: '191px', width: '267px'}}
              />
            </div>
            <div className="absolute" style={{left: '19.13px',  top: '-51.38px'}}>
              <img
                src="/newyorker.jpeg"
                alt="newyorker"
                style={{opacity: 0.2, height: '272px', width: '198px'}}
              />
            </div>
            <div className="absolute" style={{left: '668.13px',  top: '568.62px'}}>
              <img
                src="/cherry.jpeg"
                alt="cherry"
                style={{opacity: 0.2, height: '188px', width: '188px'}}
              />
            </div>
            <div className="absolute" style={{left: '1024.13px',  top: '-176.38px'}}>
              <img
                src="/ace.jpeg"
                alt="ace"
                style={{opacity: 0.2, height: '275px', width: '193px'}}
              />
            </div>
            <div className="absolute" style={{left: '793.13px',  top: '271.62px'}}>
              <img
                src="/icecream.jpeg"
                alt="icecream"
                style={{opacity: 0.2, height: '129px', width: '181px'}}
              />
            </div>
            <div className="absolute" style={{left: '490.13px',  top: '154.62px'}}>
              <img
                src="/swan.jpeg"
                alt="swan"
                style={{opacity: 0.2, height: '196px', width: '261px'}}
              />
            </div>
            <div className="absolute" style={{left: '268.13px',  top: '340.62px'}}>
              <img
                src="/malibu.jpeg"
                alt="malibu"
                style={{opacity: 0.2, height: '134px', width: '163px'}}
              />
            </div>
            <div className="absolute" style={{left: '-61.87px',  top: '447.62px'}}>
              <img
                src="/cake.jpeg"
                alt="cake"
                style={{opacity: 0.2, height: '152px', width: '229px'}}
              />
            </div>
            <div className="absolute" style={{left: '-3.87px',  top: '622.62px'}}>
              <img
                src="/cat.jpeg"
                alt="cat"
                style={{opacity: 0.2, height: '150px', width: '201px'}}
              />
            </div>
            <div className="absolute" style={{left: '1308px',  top: '496px'}}>
              <img
                src="/rome.jpeg"
                alt="rome"
                style={{opacity: 0.2, height: '309px', width: '206px'}}
              />
            </div>
            <div className="absolute" style={{left: '1268px',  top: '257px'}}>
              <img
                src="/pomegranate.jpeg"
                alt="pomegranate"
                style={{opacity: 0.2, height: '200px', width: '150px'}}
              />
            </div>
            <div className="absolute" style={{left: '1273px',  top: '-30px'}}>
              <img
                  src="/wave.jpeg"
                  alt="wave"
                  style={{opacity: 0.2, height: '258px', width: '212px'}}
                />
            </div>
            <div className="absolute" style={{left: '509px',  top: '368px'}}>
              <img
                src="/water.jpeg"
                alt="water"
                style={{opacity: 0.2, height: '186px', width: '248px'}}
              />
            </div>
            <div className="absolute" style={{left: '490px',  top: '572px'}}>
              <img
                src="/phone.jpeg"
                alt="phone"
                style={{opacity: 0.2, height: '208px', width: '138px'}}
              />
            </div>
              {/* Footer Note */}
            <div className="text-white text-center mt-10 p-5">
              <p className="text-lg">More coming soon!</p>
            </div>
          </div>
        </section>
        <section id="contact" className="relative min-h-screen bg-[#292728] flex justify-center z-10">
          <div className="absolute inset-0 bg-[#292728]"></div>
          <div className="absolute inset-0 bg-[url('/theend.jpeg')] bg-cover bg-center opacity-45">
          </div>
          <div className="relative z-30 text-white">
            <div>
              <motion.h1 className="text-5xl p-40 flex justify-center items-center text-center"
                variants={fadeInAnimationVariants}
                initial="initial"
                whileInView="animate"
              >
                {`Let's Chat!`}</motion.h1>
            </div>
            <motion.div className="bg-black bg-opacity-25 -mt-20 p-10 rounded-lg shadow-lg w-full overflow-hidden"
             variants={fadeInAnimationVariants}
             initial="initial"
             whileInView="animate"
            >
              <Contact />
              <div className="flex justify-center py-5 gap-10 text-2xl">
                <a href="https://www.linkedin.com/in/juwayriya-rizwan-201974311/" target="_blank" rel="noopener noreferrer">
                  <AiFillLinkedin/>
                </a>
                <a href="https://github.com/juwayriyarizwan" target="_blank" rel="noopener noreferrer">
                  <AiFillGithub/>
                </a>
              </div>
            </motion.div>
            <footer className="text-white text-sm py-5">
              <div className="mx-auto text-center mb-0">
                <p>&copy; 2024 Juwayriya Rizwan</p>
              </div>
            </footer>
          </div>
        </section>
      </main>
    </div>
  );
}
